from enum import Enum


class Signals(Enum):
    SOURCE_ID_EXISTS = 1
    PROFILE_EXISTS = 2
    CONNECTION_MODERATOR_PROFILE_EXISTS = 3
    CONNECTION_PROFILE_SOURCE_EXISTS = 4
    NO_MORE_THAN_ONE_ACCOUNT_FOR_PROFILE = 5
    PROFILE_ADDED = 6
    SOURCE_ADDED = 7
    NO_SUCH_RES_ID_IN_DATABASE = 8
    NO_CONNECTION_BETWEEN_PROFILE_AND_PARTICULAR_SOURCE_ID = 9
    UPDATED_CONNECTION_BETWEEN_PROFILE_AND_SOURCE = 10
    BAD_REQUEST = 11
    WRONG_MODERATOR_ID = 12

    def __str__(self):
        return f'{self.name}'
